export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SINGUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";


//PLANT CRUD

export const FETCH_PLANT_START = "FETCH_PLANT_START";
export const FETCH_PLANT_SUCCESS = "FETCH_PLANT_SUCCESS";
export const FETCH_PLANT_FAILURE = "FETCH_PLANT_FAILURE";

export const ADD_PLANT_START = "ADD_PLANT_START";
export const ADD_PLANT_SUCCESS = "ADD_PLANT_SUCCESS";
export const ADD_PLANT_FAILURE = "ADD_PLANT_FAILURE";

export const UPDATE_PLANT_START = "UPDATE_PLANT_START";
export const UPDATE_PLANT_SUCCESS = "UPDATE_PLANT_SUCCESS";
export const UPDATE_PLANT_FAILURE = "UPDATE_PLANT_FAILURE";

export const DELETE_PLANT_START = "FAILURE_PLANT_START";
export const DELETE_PLANT_SUCCESS = "FAILURE_PLANT_SUCCESS";
export const DELETE_PLANT_FAILURE = "FAILURE_PLANT_FAILURE";
